import { Skin, GameTheme } from './types';

// Let's draw 20x20 pixel maps for skins
// ' ' is transparent, 'X' is skin color, 'E' is eye color, 'A' is accessory color (e.g., headband, horns, bow)
export const SKINS: Skin[] = [
  {
    id: 'classic',
    name: 'Classic Dino',
    description: 'The iconic T-Rex runner.',
    price: 0,
    color: '#535353',
    pixels: [
      '       XXXXXX       ',
      '      XXXXXXXX      ',
      '      XEXXXXXX      ',
      '      XXXXXXXX      ',
      '      XXXX          ',
      '      XXXXXXX       ',
      'X    XXXXXXXXX      ',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XXXXXX          ',
      '     XX XX          ',
      '     X   X          ',
      '     X   X          ',
      '     XX  XX         '
    ],
    duckPixels: [
      '                    ',
      '                    ',
      '                    ',
      '       XXXXXXXXXXXX ',
      '      XXXXXXXXXXXXXX',
      '      XEXXXXXXXXXXXX',
      '      XXXXXXXXXXXXXX',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XX  XX          ',
      '    X    X          ',
      '    X    X          ',
      '    XX   XX         ',
      '                    '
    ]
  },
  {
    id: 'mech',
    name: 'Cyber Mecha',
    description: 'Plated iron dino with energy eyes.',
    price: 15,
    color: '#00f0ff',
    pixels: [
      '       AAAAAA       ',
      '      AAAXXAAA      ',
      '      AAEXXAAA      ',
      '      AAAAAA        ',
      '      AAXX          ',
      '   X  AXXXXX        ',
      '  XX AXXXXXXXX      ',
      ' XXX AAXXXXXX       ',
      'XXXXX XXXXXXX       ',
      'XXXXAXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  AAXXXXXAA         ',
      '   AXXXXXA          ',
      '    AXXXA           ',
      '    AX AX           ',
      '    X   X           ',
      '    X   X           ',
      '    XX  XX          '
    ],
    duckPixels: [
      '                    ',
      '                    ',
      '                    ',
      '       AAAAAAAAAAAA ',
      '      AAAXXAAAAAAAAA',
      '      AAEXXAAAAAAAAA',
      '      AAAAAAAAAAAAAA',
      'X    AAXXXXXX       ',
      'XX  AXXXXXXXXX      ',
      'XXXXAXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  AAXXXXXAA         ',
      '   AXXXXXA          ',
      '    AX  AX          ',
      '    X    X          ',
      '    X    X          ',
      '    XX   XX         ',
      '                    '
    ]
  },
  {
    id: 'ninja',
    name: 'Ninja Dino',
    description: 'Stalks cacti in the night shadow.',
    price: 35,
    color: '#e11d48',
    pixels: [
      '       AAAAAA  A A  ', // band trailing ties
      '      AAXXXXAA  A   ',
      '      AAEXXXAA      ',
      '      AAXXXXAA      ',
      '      XXXX          ',
      '      XXXXXXX       ',
      'X    XXXXXXXXX      ',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XXXXXX          ',
      '     XX XX          ',
      '     X   X          ',
      '     X   X          ',
      '     XX  XX         '
    ],
    duckPixels: [
      '                    ',
      '                    ',
      '                    ',
      '       AAAAAAAAAA   ',
      '      AAXXXXXAA A A ',
      '      AAEXXXAA   A  ',
      '      AAXXXXAA      ',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XX  XX          ',
      '    X    X          ',
      '    X    X          ',
      '    XX   XX         ',
      '                    '
    ]
  },
  {
    id: 'dragon',
    name: 'Tiny Dragon',
    description: 'Cute miniature dragon that breathes sparks.',
    price: 60,
    color: '#16a34a',
    pixels: [
      '    A  XXXXXX       ', // horn A
      '   AA XXXXXXXX      ',
      '  AA  XEXXXXXX      ',
      '  A   XXXXXXXX      ',
      '  A   XXXX          ',
      '      XXXXXXX  A    ', // wings A
      'X    XXXXXXXXXAA    ',
      'X    XXXXXXXXAAA    ',
      'XX  XXXXXXXXX AA    ',
      'XXXXXXXXXXXXX       ',
      ' XXXXXXXXXXX        ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XXXXXX          ',
      '     XX XX          ',
      '     X   X          ',
      '     X   X          ',
      '     XX  XX         '
    ],
    duckPixels: [
      '                    ',
      '                    ',
      '    A               ',
      '   AA  XXXXXXXXXXXX ',
      '  AA  XXXXXXXXXXXXXX',
      '  A   XEXXXXXXXXXXXX',
      '  A   XXXXXXXXXXXXXX',
      'X    XXXXXXXX  A    ',
      'XX  XXXXXXXXX AA    ',
      'XXXXXXXXXXXXXAAA    ',
      ' XXXXXXXXXXX  AA    ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XX  XX          ',
      '    X    X          ',
      '    X    X          ',
      '    XX   XX         ',
      '                    '
    ]
  },
  {
    id: 'kitty',
    name: 'Neko Dino',
    description: 'Meows when jumping. Extremely sweet.',
    price: 90,
    color: '#db2777',
    pixels: [
      '      A      A      ', // ears
      '      XXXXXXXX      ',
      '      XEXXXXXX      ',
      '      XXXXXXXX      ',
      '      XXXX          ',
      '      XXXXXXX       ',
      'X    XXXXXXXXX      ',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX  AA   ', // cute tail A
      ' XXXXXXXXXXX   A    ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XXXXXX          ',
      '     XX XX          ',
      '     X   X          ',
      '     X   X          ',
      '     XX  XX         '
    ],
    duckPixels: [
      '                    ',
      '      A      A      ',
      '      XXXXXXXXXXXX  ',
      '      XEXXXXXXXXXX  ',
      '      XXXXXXXXXXXX  ',
      '      XXXXXXXX      ',
      'X    XXXXXXXX       ',
      'XX  XXXXXXXXXX      ',
      'XXXXXXXXXXXXX  AA   ',
      ' XXXXXXXXXXX   A    ',
      '  XXXXXXXXX         ',
      '   XXXXXXX          ',
      '    XXXXXX          ',
      '    XX  XX          ',
      '    X    X          ',
      '    X    X          ',
      '    XX   XX         ',
      '                    '
    ]
  }
];

export const THEMES: GameTheme[] = [
  {
    id: 'classic',
    name: 'Classic Grey',
    background: 'bg-[#f7f7f7] border-gray-200 text-gray-800',
    canvasBg: '#f7f7f7',
    groundColor: '#d3d3d3',
    textColor: '#535353',
    accentColor: '#3b82f6',
    obstacleColor: '#535353',
    coinColor: '#eab308'
  },
  {
    id: 'cyberpunk',
    name: 'Neon Grid',
    background: 'bg-zinc-950 border-cyan-500/30 text-cyan-400',
    canvasBg: '#09090b',
    groundColor: '#3f3f46',
    textColor: '#00f0ff',
    accentColor: '#ec4899',
    obstacleColor: '#f43f5e',
    coinColor: '#facc15'
  },
  {
    id: 'sunset',
    name: 'Cozy Sunset',
    background: 'bg-gradient-to-b from-orange-200 to-amber-100 border-orange-300 text-amber-900',
    canvasBg: '#fed7aa',
    groundColor: '#f59e0b',
    textColor: '#78350f',
    accentColor: '#dc2626',
    obstacleColor: '#451a03',
    coinColor: '#dc2626'
  },
  {
    id: 'spectral',
    name: 'Graveyard Glow',
    background: 'bg-slate-950 border-purple-500/20 text-indigo-400',
    canvasBg: '#020617',
    groundColor: '#1e1b4b',
    textColor: '#818cf8',
    accentColor: '#4ade80',
    obstacleColor: '#a855f7',
    coinColor: '#a3e635'
  },
  {
    id: 'matrix',
    name: 'Terminal 1999',
    background: 'bg-[#0a0f0d] border-green-500/40 text-green-400 font-mono',
    canvasBg: '#050806',
    groundColor: '#0a2312',
    textColor: '#22c55e',
    accentColor: '#10b981',
    obstacleColor: '#22c55e',
    coinColor: '#86efac'
  }
];
